### ISSUE TITLE
Exit Game button not working.

### ISSUE THREAD

**Issue by devin7821** [Sourdough-Games/Pawn-Shop-Simulator#42] opened 2024-04-14 05:57 UTC
The image shows what happens when I hit the main menu exit button, menu just disappears.
![FailedToExit](https://github.com/Sourdough-Games/Pawn-Shop-Simulator/assets/121152485/a54c6712-71d2-4b5c-b9bc-30909477bf21)

**Comment by GrumpyCrouton** [comment] 2024-04-15 17:13
At least you still get to watch that guy dance

**Comment by GrumpyCrouton** [comment] 2024-04-18 01:49
Duplicate of #48

**Closed by GrumpyCrouton** 2024-04-18 01:49 UTC
Labels: bug
